### ISSUE TITLE
Kaggle breaks previous features

### ISSUE THREAD

**Issue by huangyz0918** [MLSysOps/MLE-agent#100]
```
(mle) ➜  MLE-agent git:(main) mle start -r
Traceback (most recent call last):
  File "/Users/huangyz0918/miniconda3/envs/mle/bin/mle", line 33, in <module>
    sys.exit(load_entry_point('mle-agent', 'console_scripts', 'mle')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huangyz0918/miniconda3/envs/mle/bin/mle", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/huangyz0918/miniconda3/envs/mle/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huangyz0918/miniconda3/envs/mle/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/huangyz0918/Desktop/MLE-agent/agent/cli.py", line 11, in <module>
    from .kaggle_cli import kaggle
  File "/Users/huangyz0918/Desktop/MLE-agent/agent/kaggle_cli.py", line 6, in <module>
    from agent.integration.kaggle_workflow import KaggleAgent
  File "/Users/huangyz0918/Desktop/MLE-agent/agent/integration/kaggle_workflow.py", line 4, in <module>
    import kaggle
  File "/Users/huangyz0918/miniconda3/envs/mle/lib/python3.11/site-packages/kaggle/__init__.py", line 7, in <module>
    api.authenticate()
  File "/Users/huangyz0918/miniconda3/envs/mle/lib/python3.11/site-packages/kaggle/api/kaggle_api_extended.py", line 398, in authenticate
    raise IOError('Could not find {}. Make sure it\'s located in'
OSError: Could not find kaggle.json. Make sure it's located in /Users/huangyz0918/.kaggle. Or use the environment method.
```

**Comment by huangyz0918** [comment]
Anyway, I am going to rebuild the whole project, no need to file a fix
