### ISSUE TITLE
Unable to use `mle chat`

### ISSUE THREAD

**Issue by Zhou-Shilin** [MLSysOps/MLE-agent#220]
#### Software execution information

MLE-agent version: Latest
System OS version: Windows 11

#### Problem description

```
 > mle chat
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\BaimoQilin\AppData\Local\Programs\Python\Python312\Scripts\mle.exe\__main__.py", line 7, in <module>
  File "C:\Users\BaimoQilin\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\BaimoQilin\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\BaimoQilin\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\BaimoQilin\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\BaimoQilin\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\BaimoQilin\AppData\Local\Programs\Python\Python312\Lib\site-packages\mle\cli.py", line 146, in chat
    if not check_config(console):
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\BaimoQilin\AppData\Local\Programs\Python\Python312\Lib\site-packages\mle\utils\system.py", line 95, in check_config
    if data.get('search_key'):
       ^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
```

#### Steps to reproduce the problem

1. `mle new DeepReasoning`
2. `cd` and `mle start`
3. `mle chat`

#### Expected behavior

Launch chat.

#### Other information

None.

**Comment by leeeizhang** [comment]
Hi, @Zhou-Shilin. Thank you for trying our MLE Agent.

It seems that your project's config file could not be successfully loaded. Please check whether the `<project_name>/.mle/config.yml` can be opened, or create a new project to avoid this issue.
